### ISSUE TITLE
拡張子の変更をお願いします。

### ISSUE THREAD

**Issue by libertyangel** [konan-pbl-2018/teamD#4]
teamD->data->stage->stage.mqo

**Comment by n-nitta** [comment]
はい、わかりました。少し待ってください。

**Comment by n-nitta** [comment]
stage.3dsに変換しました。同じフォルダにあります。確認してください。

**Comment by libertyangel** [comment]
変換後
色がなくなっています。

**Comment by n-nitta** [comment]
stage.objに変換してみました。（stage.mtlも一緒に使います。）
試してみてください。
