### ISSUE TITLE
拡張子の変更お願いします

### ISSUE THREAD

**Issue by libertyangel** [konan-pbl-2018/teamD#6]
teamD->data->stage->stage.mqo
teamD->data->character->enemy1.mqo
teamD->data->character->yuusya.mqo
以上の3つをお願いします。

**Comment by n-nitta** [comment]
stage.mqoだけ、stage.obj、stage2.obj、stage3.obj、stage4.objに変換しました。

**Comment by n-nitta** [comment]
teamD->data->character->enemy1.mqo
teamD->data->character->yuusya.mqo

これらもobjファイルに変換しました。
