### ISSUE TITLE
キャラクターの位置が-150以下になると背景が黒くなる

### ISSUE THREAD

**Issue by Ogino015** [konan-pbl-2018/teamD#8]
ステージを進みキャラクターの位置がー１５０以下になると背景画像が黒くなる。（－１５０以上まで戻るとまた見える）
背景が黒くなった後、数十秒たつと一部の足場と敵の判定が消えてしまう。

**Comment by n-nitta** [comment]
足場の判定はプレイヤーのZ座標が少しずつずれてきているためかもしれません。
progress()メソッドの中に、

player.getActor().setPosition(player.getActor().getPosition().setZ(0.0));

のような処理を入れて、プレイヤーのZ座標の値が常に0になるようにしてみてください。

**Comment by n-nitta** [comment]
フレームワークのGround2Dを修正しました。
