### ISSUE TITLE
拡張子の変更をお願いします。

### ISSUE THREAD

**Issue by libertyangel** [konan-pbl-2018/teamD#9]
teamD->data->stage->stage.mqo
teamD->data->character->enemy２.mqo
teamD->data->character->boss.mqo
teamD->data->character->sword.mqo
以上の4つをお願いします。

**Comment by n-nitta** [comment]
変換しました。
stage.mqo ==> stage1.obj, stage2.obj, stage3.obj or stage4.obj
enemy2.mqo ==> enemy2.obj, enemy2_2.obj, enemy2_3.obj or enemy2_4.obj
boss.mqo ==> boss.obj, boss2.obj, boss3.obj or boss4.obj
sword.mqo ==> sword.obj, sword2.obj, sword3.obj or sword4.obj
